version: "3.7"

services:
  rabbitmq:
    build: .
    environment:
      - TCP_PORTS=15672, 5672
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]
    ports:
      - 15672:15672
      - 5672:5672